matching = {
    "rust": "rust",
    "valheim": "valheim",
    "minecraft": "mc",
    "mta": "mta",
    "unturned": "unturned",
    "gta5": "altv",
    "left 4 dead": "l4d",
    "killing floor szerver": "kf",
    "call of duty 2": "cod2",
    "call of duty 1": "cod1",
    "jedi academy": "jkja",
    "minecraft pocket edition": "mcpe",
    "cs 1.6": "cs",
    "call of duty 5 world at war": "cod5",
    "call of duty united offensive": "coduo",
    "call of duty 4 modern warfare": "cod4",
    "scp secret laboratory": "scpsl",
    "counter strike source": "css",
    "san andreas multiplayer": "samp",
    "counter strike condition zero": "cscz",
    "cs:go": "csgo",
    "teamspeak 3": "ts3",
    "teamspeak 3 musicbot": "ts3mb"
}